echo "字符串   数值      为真，如果"
echo "x=y      x -eq y   x等于y"
echo "x!=y     x -ne y   x不等于y"
echo "x<y      x -lt y   x小于y"
echo "x<=y     x -le y   x小于等于y"
echo "x>y      x -gt y   x大于y"
echo "x>=y     x -ge y   x大于等于y"
echo "-n x     -         x不为空"
echo "-z x     -         x为空"
